### PR TITLE
Set version 2.0 to Retired to remove docs from dev hub

### PR DESCRIPTION
**Pull request by Tateni93**

### CODE REVIEW

**Comment by LetMeTestThat** [comment]
The change looks good but we will also need to edit the stub's definition so when users hit the `/api/definition` endpoint, the response tells them that version 2.0 is 'RETIRED' rather than 'DEPRECIATED'

This file can be found in /app/views/

**Comment by Tateni93** [comment]
> The change looks good but we will also need to edit the stub's definition so when users hit the `/api/definition` endpoint, the response tells them that version 2.0 is 'RETIRED' rather than 'DEPRECIATED'
> 
> This file can be found in `/app/views/`

Thanks, I have committed this change now.

**Comment by LetMeTestThat** [comment]
> > The change looks good but we will also need to edit the stub's definition so when users hit the `/api/definition` endpoint, the response tells them that version 2.0 is 'RETIRED' rather than 'DEPRECIATED'
> > This file can be found in `/app/views/`
> 
> Thanks, I have committed this change now.

Looks good! Are you okay to squash the commits? I'll happily merge the changes then.

**Comment by Tateni93** [comment]
> > > The change looks good but we will also need to edit the stub's definition so when users hit the `/api/definition` endpoint, the response tells them that version 2.0 is 'RETIRED' rather than 'DEPRECIATED'
> > > This file can be found in `/app/views/`
> > 
> > 
> > Thanks, I have committed this change now.
> 
> Looks good! Are you okay to squash the commits? I'll happily merge the changes then.

Hi, normally I would do this on merge from the dropdown. I don't have write access to this repo so can't do it from there. Would this be something you could do on merge?

**Pull request merged**
